// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pb.proto

package pb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type DeHeartbeat struct {
	CPU                  uint32   `protobuf:"varint,1,opt,name=CPU,proto3" json:"CPU,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeHeartbeat) Reset()         { *m = DeHeartbeat{} }
func (m *DeHeartbeat) String() string { return proto.CompactTextString(m) }
func (*DeHeartbeat) ProtoMessage()    {}
func (*DeHeartbeat) Descriptor() ([]byte, []int) {
	return fileDescriptor_f80abaa17e25ccc8, []int{0}
}

func (m *DeHeartbeat) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeHeartbeat.Unmarshal(m, b)
}
func (m *DeHeartbeat) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeHeartbeat.Marshal(b, m, deterministic)
}
func (m *DeHeartbeat) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeHeartbeat.Merge(m, src)
}
func (m *DeHeartbeat) XXX_Size() int {
	return xxx_messageInfo_DeHeartbeat.Size(m)
}
func (m *DeHeartbeat) XXX_DiscardUnknown() {
	xxx_messageInfo_DeHeartbeat.DiscardUnknown(m)
}

var xxx_messageInfo_DeHeartbeat proto.InternalMessageInfo

func (m *DeHeartbeat) GetCPU() uint32 {
	if m != nil {
		return m.CPU
	}
	return 0
}

type DeShell struct {
	Cmd                  string   `protobuf:"bytes,1,opt,name=Cmd,proto3" json:"Cmd,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeShell) Reset()         { *m = DeShell{} }
func (m *DeShell) String() string { return proto.CompactTextString(m) }
func (*DeShell) ProtoMessage()    {}
func (*DeShell) Descriptor() ([]byte, []int) {
	return fileDescriptor_f80abaa17e25ccc8, []int{1}
}

func (m *DeShell) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeShell.Unmarshal(m, b)
}
func (m *DeShell) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeShell.Marshal(b, m, deterministic)
}
func (m *DeShell) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeShell.Merge(m, src)
}
func (m *DeShell) XXX_Size() int {
	return xxx_messageInfo_DeShell.Size(m)
}
func (m *DeShell) XXX_DiscardUnknown() {
	xxx_messageInfo_DeShell.DiscardUnknown(m)
}

var xxx_messageInfo_DeShell proto.InternalMessageInfo

func (m *DeShell) GetCmd() string {
	if m != nil {
		return m.Cmd
	}
	return ""
}

type DeUpload struct {
	Body                 []byte   `protobuf:"bytes,1,opt,name=Body,proto3" json:"Body,omitempty"`
	FileName             string   `protobuf:"bytes,2,opt,name=FileName,proto3" json:"FileName,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeUpload) Reset()         { *m = DeUpload{} }
func (m *DeUpload) String() string { return proto.CompactTextString(m) }
func (*DeUpload) ProtoMessage()    {}
func (*DeUpload) Descriptor() ([]byte, []int) {
	return fileDescriptor_f80abaa17e25ccc8, []int{2}
}

func (m *DeUpload) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeUpload.Unmarshal(m, b)
}
func (m *DeUpload) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeUpload.Marshal(b, m, deterministic)
}
func (m *DeUpload) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeUpload.Merge(m, src)
}
func (m *DeUpload) XXX_Size() int {
	return xxx_messageInfo_DeUpload.Size(m)
}
func (m *DeUpload) XXX_DiscardUnknown() {
	xxx_messageInfo_DeUpload.DiscardUnknown(m)
}

var xxx_messageInfo_DeUpload proto.InternalMessageInfo

func (m *DeUpload) GetBody() []byte {
	if m != nil {
		return m.Body
	}
	return nil
}

func (m *DeUpload) GetFileName() string {
	if m != nil {
		return m.FileName
	}
	return ""
}

type DeDownLoad struct {
	FilePath             string   `protobuf:"bytes,1,opt,name=FilePath,proto3" json:"FilePath,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeDownLoad) Reset()         { *m = DeDownLoad{} }
func (m *DeDownLoad) String() string { return proto.CompactTextString(m) }
func (*DeDownLoad) ProtoMessage()    {}
func (*DeDownLoad) Descriptor() ([]byte, []int) {
	return fileDescriptor_f80abaa17e25ccc8, []int{3}
}

func (m *DeDownLoad) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeDownLoad.Unmarshal(m, b)
}
func (m *DeDownLoad) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeDownLoad.Marshal(b, m, deterministic)
}
func (m *DeDownLoad) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeDownLoad.Merge(m, src)
}
func (m *DeDownLoad) XXX_Size() int {
	return xxx_messageInfo_DeDownLoad.Size(m)
}
func (m *DeDownLoad) XXX_DiscardUnknown() {
	xxx_messageInfo_DeDownLoad.DiscardUnknown(m)
}

var xxx_messageInfo_DeDownLoad proto.InternalMessageInfo

func (m *DeDownLoad) GetFilePath() string {
	if m != nil {
		return m.FilePath
	}
	return ""
}

type DeGeneralResp struct {
	Bytes                []byte   `protobuf:"bytes,1,opt,name=Bytes,proto3" json:"Bytes,omitempty"`
	Body                 string   `protobuf:"bytes,2,opt,name=Body,proto3" json:"Body,omitempty"`
	Success              bool     `protobuf:"varint,3,opt,name=Success,proto3" json:"Success,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeGeneralResp) Reset()         { *m = DeGeneralResp{} }
func (m *DeGeneralResp) String() string { return proto.CompactTextString(m) }
func (*DeGeneralResp) ProtoMessage()    {}
func (*DeGeneralResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_f80abaa17e25ccc8, []int{4}
}

func (m *DeGeneralResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeGeneralResp.Unmarshal(m, b)
}
func (m *DeGeneralResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeGeneralResp.Marshal(b, m, deterministic)
}
func (m *DeGeneralResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeGeneralResp.Merge(m, src)
}
func (m *DeGeneralResp) XXX_Size() int {
	return xxx_messageInfo_DeGeneralResp.Size(m)
}
func (m *DeGeneralResp) XXX_DiscardUnknown() {
	xxx_messageInfo_DeGeneralResp.DiscardUnknown(m)
}

var xxx_messageInfo_DeGeneralResp proto.InternalMessageInfo

func (m *DeGeneralResp) GetBytes() []byte {
	if m != nil {
		return m.Bytes
	}
	return nil
}

func (m *DeGeneralResp) GetBody() string {
	if m != nil {
		return m.Body
	}
	return ""
}

func (m *DeGeneralResp) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

type Resp struct {
	// Types that are valid to be assigned to RespItem:
	//	*Resp_Shell
	//	*Resp_Heartbeat
	//	*Resp_Upload
	//	*Resp_DownLoad
	//	*Resp_GeneralResp
	RespItem             isResp_RespItem `protobuf_oneof:"RespItem"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *Resp) Reset()         { *m = Resp{} }
func (m *Resp) String() string { return proto.CompactTextString(m) }
func (*Resp) ProtoMessage()    {}
func (*Resp) Descriptor() ([]byte, []int) {
	return fileDescriptor_f80abaa17e25ccc8, []int{5}
}

func (m *Resp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Resp.Unmarshal(m, b)
}
func (m *Resp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Resp.Marshal(b, m, deterministic)
}
func (m *Resp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Resp.Merge(m, src)
}
func (m *Resp) XXX_Size() int {
	return xxx_messageInfo_Resp.Size(m)
}
func (m *Resp) XXX_DiscardUnknown() {
	xxx_messageInfo_Resp.DiscardUnknown(m)
}

var xxx_messageInfo_Resp proto.InternalMessageInfo

type isResp_RespItem interface {
	isResp_RespItem()
}

type Resp_Shell struct {
	Shell *DeShell `protobuf:"bytes,1,opt,name=Shell,proto3,oneof"`
}

type Resp_Heartbeat struct {
	Heartbeat *DeHeartbeat `protobuf:"bytes,2,opt,name=Heartbeat,proto3,oneof"`
}

type Resp_Upload struct {
	Upload *DeUpload `protobuf:"bytes,3,opt,name=Upload,proto3,oneof"`
}

type Resp_DownLoad struct {
	DownLoad *DeDownLoad `protobuf:"bytes,4,opt,name=DownLoad,proto3,oneof"`
}

type Resp_GeneralResp struct {
	GeneralResp *DeGeneralResp `protobuf:"bytes,5,opt,name=GeneralResp,proto3,oneof"`
}

func (*Resp_Shell) isResp_RespItem() {}

func (*Resp_Heartbeat) isResp_RespItem() {}

func (*Resp_Upload) isResp_RespItem() {}

func (*Resp_DownLoad) isResp_RespItem() {}

func (*Resp_GeneralResp) isResp_RespItem() {}

func (m *Resp) GetRespItem() isResp_RespItem {
	if m != nil {
		return m.RespItem
	}
	return nil
}

func (m *Resp) GetShell() *DeShell {
	if x, ok := m.GetRespItem().(*Resp_Shell); ok {
		return x.Shell
	}
	return nil
}

func (m *Resp) GetHeartbeat() *DeHeartbeat {
	if x, ok := m.GetRespItem().(*Resp_Heartbeat); ok {
		return x.Heartbeat
	}
	return nil
}

func (m *Resp) GetUpload() *DeUpload {
	if x, ok := m.GetRespItem().(*Resp_Upload); ok {
		return x.Upload
	}
	return nil
}

func (m *Resp) GetDownLoad() *DeDownLoad {
	if x, ok := m.GetRespItem().(*Resp_DownLoad); ok {
		return x.DownLoad
	}
	return nil
}

func (m *Resp) GetGeneralResp() *DeGeneralResp {
	if x, ok := m.GetRespItem().(*Resp_GeneralResp); ok {
		return x.GeneralResp
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*Resp) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*Resp_Shell)(nil),
		(*Resp_Heartbeat)(nil),
		(*Resp_Upload)(nil),
		(*Resp_DownLoad)(nil),
		(*Resp_GeneralResp)(nil),
	}
}

func init() {
	proto.RegisterType((*DeHeartbeat)(nil), "pb.deHeartbeat")
	proto.RegisterType((*DeShell)(nil), "pb.deShell")
	proto.RegisterType((*DeUpload)(nil), "pb.deUpload")
	proto.RegisterType((*DeDownLoad)(nil), "pb.deDownLoad")
	proto.RegisterType((*DeGeneralResp)(nil), "pb.deGeneralResp")
	proto.RegisterType((*Resp)(nil), "pb.Resp")
}

func init() {
	proto.RegisterFile("pb.proto", fileDescriptor_f80abaa17e25ccc8)
}

var fileDescriptor_f80abaa17e25ccc8 = []byte{
	// 316 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x4c, 0x91, 0x4f, 0x4b, 0x03, 0x31,
	0x10, 0xc5, 0x77, 0xfb, 0x77, 0x3b, 0xdb, 0xfa, 0x27, 0x78, 0x08, 0x7a, 0xb0, 0x44, 0x90, 0x1e,
	0xa4, 0x42, 0xc5, 0x8b, 0xc7, 0x2a, 0x1a, 0x41, 0xa4, 0xa4, 0xf4, 0x03, 0x64, 0x9b, 0x81, 0x0a,
	0xdb, 0x6e, 0xe8, 0x46, 0xa4, 0x1f, 0xdc, 0xbb, 0xec, 0x64, 0x1b, 0xf7, 0xb4, 0x33, 0xf3, 0x7e,
	0x93, 0x97, 0xbc, 0x85, 0xc4, 0x66, 0x53, 0xbb, 0x2f, 0x5c, 0xc1, 0x5a, 0x36, 0x13, 0xd7, 0x90,
	0x1a, 0x94, 0xa8, 0xf7, 0x2e, 0x43, 0xed, 0xd8, 0x19, 0xb4, 0x9f, 0x17, 0x2b, 0x1e, 0x8f, 0xe3,
	0xc9, 0x48, 0x55, 0xa5, 0xb8, 0x82, 0xbe, 0xc1, 0xe5, 0x06, 0xf3, 0x9c, 0xc4, 0xad, 0x21, 0x71,
	0xa0, 0xaa, 0x52, 0x3c, 0x41, 0x62, 0x70, 0x65, 0xf3, 0x42, 0x1b, 0xc6, 0xa0, 0x33, 0x2f, 0xcc,
	0x81, 0xe4, 0xa1, 0xa2, 0x9a, 0x5d, 0x42, 0xf2, 0xfa, 0x95, 0xe3, 0xa7, 0xde, 0x22, 0x6f, 0xd1,
	0x5a, 0xe8, 0xc5, 0x04, 0xc0, 0xe0, 0x4b, 0xf1, 0xb3, 0xfb, 0xa8, 0xb6, 0x6b, 0x72, 0xa1, 0xdd,
	0xa6, 0x36, 0x08, 0xbd, 0x58, 0xc2, 0xc8, 0xe0, 0x1b, 0xee, 0x70, 0xaf, 0x73, 0x85, 0xa5, 0x65,
	0x17, 0xd0, 0x9d, 0x1f, 0x1c, 0x96, 0xb5, 0x97, 0x6f, 0xc2, 0x05, 0xbc, 0x91, 0xbf, 0x00, 0x87,
	0xfe, 0xf2, 0x7b, 0xbd, 0xc6, 0xb2, 0xe4, 0xed, 0x71, 0x3c, 0x49, 0xd4, 0xb1, 0x15, 0xbf, 0x31,
	0x74, 0xe8, 0xb0, 0x1b, 0xe8, 0xd2, 0xf3, 0xe8, 0xb0, 0x74, 0x96, 0x4e, 0x6d, 0x36, 0xad, 0x5f,
	0x2c, 0x23, 0xe5, 0x35, 0x76, 0x0f, 0x83, 0x10, 0x12, 0x19, 0xa4, 0xb3, 0x53, 0x0f, 0x86, 0xb1,
	0x8c, 0xd4, 0x3f, 0xc3, 0x6e, 0xa1, 0xe7, 0x73, 0x21, 0xdf, 0x74, 0x36, 0xf4, 0xb4, 0x9f, 0xc9,
	0x48, 0xd5, 0x2a, 0xbb, 0x83, 0xe4, 0x98, 0x01, 0xef, 0x10, 0x79, 0xe2, 0xc9, 0xe3, 0x54, 0x46,
	0x2a, 0x10, 0xec, 0x11, 0xd2, 0x46, 0x0e, 0xbc, 0x4b, 0x0b, 0xe7, 0x7e, 0xa1, 0x21, 0xc8, 0x48,
	0x35, 0xb9, 0x39, 0x40, 0x52, 0x7d, 0xdf, 0x1d, 0x6e, 0xb3, 0x1e, 0xfd, 0xfb, 0x87, 0xbf, 0x00,
	0x00, 0x00, 0xff, 0xff, 0x9b, 0x9b, 0xa4, 0x10, 0x07, 0x02, 0x00, 0x00,
}
